name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my code
        uses: actions/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artfactv@2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          PATH: .
   main:
    runs-on: windows-latest
    steps:
      - name: Check out my code
        uses: actions/checkout@v2
      - name: Upload the artifact
        uses: actions/upload-artfactv@2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          PATH: .
